/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.crud.panels;

import hospital.Hospital;
import hospital.HospitalDirectory;
import javax.swing.JOptionPane;
import rbac.context.RbacApplicationContext;
import ui.HomeScreen;
import ui.HomeScreenNotDefault;
import us.state.city.City;
import us.state.city.community.Community;
import utility.RegexConstants;
import utility.ValidationHelper;

/**
 *
 * @author rohitpanicker
 */
public class HospitalCrud extends javax.swing.JPanel {

    /**
     * Creates new form HospitalCrud
     */
    
    public String operation;
    public Hospital hospital;
    public HospitalCrud(String operation) {
        
        this.operation = operation;
        initComponents();
    }
    
    public HospitalCrud(Hospital hospital,String operation) {
       
        initComponents();
        this.operation = operation;
        this.hospital = hospital;
         if(operation.equals("populate"))
        {  createDoctorBtn.setVisible(false);
           populateTable(hospital);
        }else if(operation.equals("update"))
        {  createDoctorBtn.setVisible(true);
           createDoctorBtn.setText("Update");
            populateTable(hospital);
            
        }
    }
    
    public void populateTable(Hospital hospital)
    {
         hospitalIdTxtField.setText(String.valueOf(hospital.getHospitalId()));
          nameTxtField.setText(hospital.getHospitalName());
           
             cityTxtField.setText(hospital.getCommunity().getCity().getName());
           stateTxtField.setText(hospital.getCommunity().getCity().getState());
          countryTxtField.setText(hospital.getCommunity().getCity().getCountry());
           
            communityNameTxtField1.setText(hospital.getCommunity().getCommunityName());
           zipCodeTxtField.setText(hospital.getCommunity().getZipCode());
             addressTxtField.setText(hospital.getCommunity().getLocation());

    }
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        logoutLabel = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        loginToContinuePanel = new javax.swing.JPanel();
        hospitalIdLabel = new javax.swing.JLabel();
        hospitalNameLabel = new javax.swing.JLabel();
        communityNameLabel = new javax.swing.JLabel();
        zipCodeLabel = new javax.swing.JLabel();
        cityLabel = new javax.swing.JLabel();
        stateLabel = new javax.swing.JLabel();
        countryLabel = new javax.swing.JLabel();
        addressLabel = new javax.swing.JLabel();
        hospitalIdTxtField = new javax.swing.JTextField();
        nameTxtField = new javax.swing.JTextField();
        addressTxtField = new javax.swing.JTextField();
        communityNameTxtField1 = new javax.swing.JTextField();
        cityTxtField = new javax.swing.JTextField();
        stateTxtField = new javax.swing.JTextField();
        zipCodeTxtField = new javax.swing.JTextField();
        countryTxtField = new javax.swing.JTextField();
        createDoctorBtn = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(0, 153, 0));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("MEDICAL RESOURCE FINDER");

        logoutLabel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        logoutLabel.setForeground(new java.awt.Color(255, 255, 255));
        logoutLabel.setText("Logout");
        logoutLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                logoutLabelMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(479, 479, 479)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(296, 296, 296)
                .addComponent(logoutLabel)
                .addGap(211, 211, 211))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                    .addComponent(logoutLabel))
                .addContainerGap())
        );

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 1390, 70));

        jPanel4.setBackground(new java.awt.Color(0, 204, 51));

        jPanel5.setBackground(new java.awt.Color(200, 248, 202));

        jLabel5.setBackground(new java.awt.Color(0, 102, 51));
        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 51));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("WELCOME");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        loginToContinuePanel.setBackground(new java.awt.Color(77, 165, 124));

        javax.swing.GroupLayout loginToContinuePanelLayout = new javax.swing.GroupLayout(loginToContinuePanel);
        loginToContinuePanel.setLayout(loginToContinuePanelLayout);
        loginToContinuePanelLayout.setHorizontalGroup(
            loginToContinuePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 260, Short.MAX_VALUE)
        );
        loginToContinuePanelLayout.setVerticalGroup(
            loginToContinuePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 169, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(loginToContinuePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loginToContinuePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(400, 400, 400))
        );

        add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 260, 860));

        hospitalIdLabel.setText("Hospital ID:");
        add(hospitalIdLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 150, 70, -1));

        hospitalNameLabel.setText("Name:");
        add(hospitalNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 220, 120, -1));

        communityNameLabel.setText("Community Name:");
        add(communityNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 300, 130, -1));

        zipCodeLabel.setText("ZipCode:");
        add(zipCodeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 730, 130, -1));

        cityLabel.setText("City:");
        add(cityLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 370, 40, -1));

        stateLabel.setText("State");
        add(stateLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 450, 40, -1));

        countryLabel.setText("Country:");
        add(countryLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 520, 60, -1));

        addressLabel.setText("Address:");
        add(addressLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 630, 130, 30));
        add(hospitalIdTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 150, 200, -1));

        nameTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTxtFieldActionPerformed(evt);
            }
        });
        add(nameTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 210, 200, -1));
        add(addressTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 600, 200, 80));
        add(communityNameTxtField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 290, 200, -1));
        add(cityTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 370, 200, -1));
        add(stateTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 450, 200, -1));
        add(zipCodeTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 730, 200, -1));
        add(countryTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 520, 200, -1));

        createDoctorBtn.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        createDoctorBtn.setText("CREATE");
        createDoctorBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createDoctorBtnActionPerformed(evt);
            }
        });
        add(createDoctorBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 780, 300, 80));
    }// </editor-fold>//GEN-END:initComponents

    private void logoutLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutLabelMousePressed
        // TODO add your handling code here:

        RbacApplicationContext rbacApplicationContext = RbacApplicationContext.getInstance();
        rbacApplicationContext.setRoleContext(null);
        rbacApplicationContext.setUser(null);
        JOptionPane.showMessageDialog(this, "Logged Out");
        HomeScreenNotDefault homeScreenNotDefault = new HomeScreenNotDefault();
        HomeScreen.homeScreen.getjSplitPane1().setRightComponent(homeScreenNotDefault);
        HomeScreen.homeScreen.getjSplitPane1().setDividerLocation(150);
    }//GEN-LAST:event_logoutLabelMousePressed

    private void nameTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTxtFieldActionPerformed

    private void createDoctorBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createDoctorBtnActionPerformed
        // TODO add your handling code here:
         int errorCount = 0;
          StringBuffer errorNotifier = new StringBuffer("Please correct the following Errors\n");
            String id = null, name = null, cityName = null , state = null, country = null, communityName = null, zipCode = null, address = null;
            
            if(ValidationHelper.isInteger(hospitalIdTxtField.getText())){
             id = hospitalIdTxtField.getText();
            }
            else{
                errorCount++;
            errorNotifier.append(errorCount).append(". Hospital ID should be an Integer\n");
            }
            
            if(ValidationHelper.isValidName(nameTxtField.getText()))
            {
             name = nameTxtField.getText();
            }else{
                errorCount++;
            errorNotifier.append(errorCount).append(". Hospital Name should be a String\n");
            }
             
            if(ValidationHelper.isValidName(cityTxtField.getText()))
            {
             cityName = cityTxtField.getText();
            }else{
                 errorCount++;
            errorNotifier.append(errorCount).append(". City Name should be a String\n");
            }
            
            if(ValidationHelper.isValidName(stateTxtField.getText())){
             state = stateTxtField.getText();
            }else{
                errorCount++;
            errorNotifier.append(errorCount).append(". State Name should be a String\n");
            }
            
            if(ValidationHelper.isValidName(countryTxtField.getText())){
             country = countryTxtField.getText();
            }else{
                 errorCount++;
            errorNotifier.append(errorCount).append(". Country Name should be a String\n");
            }
           
            if(ValidationHelper.isValidName(communityNameTxtField1.getText())){
             communityName = communityNameTxtField1.getText();
            }else{
                errorCount++;
            errorNotifier.append(errorCount).append(". Community Name should be a String\n");
            }
            if(ValidationHelper.isInteger(zipCodeTxtField.getText()))
            {
             zipCode = zipCodeTxtField.getText();
            }else{
                errorCount++;
            errorNotifier.append(errorCount).append(". ZipCode should be an Integer\n");
            }
            
            if(ValidationHelper.isValidName(addressTxtField.getText())){
             address = addressTxtField.getText();
            }else{
                errorCount++;
            errorNotifier.append(errorCount).append(". Address should be a String\n");
            }
            
            if(errorCount > 0 )
            {
                 JOptionPane.showMessageDialog(this, errorNotifier.toString());
            }
            else{
            City city = new City(state, country,  cityName);
            Community community = new Community(city, communityName, country, zipCode);
            if(operation.contains("create")){
            Hospital hospital = new Hospital(cityName, community, Integer.parseInt(id));
            HospitalDirectory.hospitalList.add(hospital);
                
               
           JOptionPane.showMessageDialog(this,"Created New Hospital");
            }else if(operation.contains("update"))
            {
            hospital.setCommunity(community);
            hospital.setHospitalId(Integer.parseInt(id));
            hospital.setHospitalName(name);
            
             JOptionPane.showMessageDialog(this,"Updated Hospital Record Successfuly");
   
            }
            }
          

      

      
    }//GEN-LAST:event_createDoctorBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addressLabel;
    private javax.swing.JTextField addressTxtField;
    private javax.swing.JLabel cityLabel;
    private javax.swing.JTextField cityTxtField;
    private javax.swing.JLabel communityNameLabel;
    private javax.swing.JTextField communityNameTxtField1;
    private javax.swing.JLabel countryLabel;
    private javax.swing.JTextField countryTxtField;
    private javax.swing.JButton createDoctorBtn;
    private javax.swing.JLabel hospitalIdLabel;
    private javax.swing.JTextField hospitalIdTxtField;
    private javax.swing.JLabel hospitalNameLabel;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel loginToContinuePanel;
    private javax.swing.JLabel logoutLabel;
    private javax.swing.JTextField nameTxtField;
    private javax.swing.JLabel stateLabel;
    private javax.swing.JTextField stateTxtField;
    private javax.swing.JLabel zipCodeLabel;
    private javax.swing.JTextField zipCodeTxtField;
    // End of variables declaration//GEN-END:variables
}
