/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.crud.panels;

import house.House;
import java.awt.Image;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import person.Person;
import rbac.context.RbacApplicationContext;
import ui.HomeScreen;
import ui.HomeScreenNotDefault;
import us.state.city.City;
import us.state.city.community.Community;
import utility.ValidationHelper;

/**
 *
 * @author rohitpanicker
 */
public class PersonCrud extends javax.swing.JPanel {

    /**
     * Creates new form PersonCrud
     */
    
    Person person = null;
    public PersonCrud(Person person) {
        initComponents();
        this.person = person;
        populateFields();
        
    }
    
    public void populateFields()
    {
        idTxtField.setText(person.getId());
        nameTxtField.setText(person.getName());
        phnNumberTxtField.setText(String.valueOf(person.getPhoneNumber()));
        zipCodeTxtField.setText(person.getResidence().getCommunity().getZipCode());
        emailIdTxtField.setText(person.getEmailid());
        cityTxtField.setText(person.getResidence().getCommunity().getCity().getName());
        stateTxtField.setText(person.getResidence().getCommunity().getCity().getState());
        countryTxtField.setText(person.getResidence().getCommunity().getCity().getCountry());
        genderTxtField.setText(person.getGender());
        ageTxtField.setText(String.valueOf(person.getAge()));
        communityNameTxtField.setText(person.getResidence().getCommunity().getCommunityName());
        addressTxtField.setText(person.getResidence().getCommunity().getLocation());
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        logoutLabel = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        loginToContinuePanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        logoutLabel1 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        loginToContinuePanel1 = new javax.swing.JPanel();
        personNameLabel = new javax.swing.JLabel();
        emailIdPersonLabel = new javax.swing.JLabel();
        phonePersonalLabel = new javax.swing.JLabel();
        cityLabel = new javax.swing.JLabel();
        stateLabel = new javax.swing.JLabel();
        countryLabel = new javax.swing.JLabel();
        genderLabel = new javax.swing.JLabel();
        ageLabel = new javax.swing.JLabel();
        addressTxtField = new javax.swing.JTextField();
        nameTxtField = new javax.swing.JTextField();
        emailIdTxtField = new javax.swing.JTextField();
        phnNumberTxtField = new javax.swing.JTextField();
        cityTxtField = new javax.swing.JTextField();
        stateTxtField = new javax.swing.JTextField();
        countryTxtField = new javax.swing.JTextField();
        genderTxtField = new javax.swing.JTextField();
        ageTxtField = new javax.swing.JTextField();
        createPatientBtn = new javax.swing.JButton();
        personIdLabel1 = new javax.swing.JLabel();
        idTxtField = new javax.swing.JTextField();
        communityNameLabel = new javax.swing.JLabel();
        communityNameTxtField = new javax.swing.JTextField();
        addressLabel = new javax.swing.JLabel();
        zipCodeLabel = new javax.swing.JLabel();
        zipCodeTxtField = new javax.swing.JTextField();
        photoLabel = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        browseButton = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(0, 153, 0));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("MEDICAL RESOURCE FINDER");

        logoutLabel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        logoutLabel.setForeground(new java.awt.Color(255, 255, 255));
        logoutLabel.setText("Logout");
        logoutLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                logoutLabelMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(479, 479, 479)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(296, 296, 296)
                .addComponent(logoutLabel)
                .addGap(211, 211, 211))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                    .addComponent(logoutLabel))
                .addContainerGap())
        );

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 1390, 70));

        jPanel4.setBackground(new java.awt.Color(0, 204, 51));

        jPanel5.setBackground(new java.awt.Color(200, 248, 202));

        jLabel5.setBackground(new java.awt.Color(0, 102, 51));
        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 51));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("WELCOME");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        loginToContinuePanel.setBackground(new java.awt.Color(77, 165, 124));

        javax.swing.GroupLayout loginToContinuePanelLayout = new javax.swing.GroupLayout(loginToContinuePanel);
        loginToContinuePanel.setLayout(loginToContinuePanelLayout);
        loginToContinuePanelLayout.setHorizontalGroup(
            loginToContinuePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 260, Short.MAX_VALUE)
        );
        loginToContinuePanelLayout.setVerticalGroup(
            loginToContinuePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 169, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(loginToContinuePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loginToContinuePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(400, 400, 400))
        );

        add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 260, 860));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(0, 153, 0));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("MEDICAL RESOURCE FINDER");

        logoutLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        logoutLabel1.setForeground(new java.awt.Color(255, 255, 255));
        logoutLabel1.setText("Logout");
        logoutLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                logoutLabel1MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(479, 479, 479)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(296, 296, 296)
                .addComponent(logoutLabel1)
                .addGap(211, 211, 211))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                    .addComponent(logoutLabel1))
                .addContainerGap())
        );

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 1390, 70));

        jPanel7.setBackground(new java.awt.Color(0, 204, 51));

        jPanel8.setBackground(new java.awt.Color(200, 248, 202));

        jLabel6.setBackground(new java.awt.Color(0, 102, 51));
        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 51));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("WELCOME");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        loginToContinuePanel1.setBackground(new java.awt.Color(77, 165, 124));

        javax.swing.GroupLayout loginToContinuePanel1Layout = new javax.swing.GroupLayout(loginToContinuePanel1);
        loginToContinuePanel1.setLayout(loginToContinuePanel1Layout);
        loginToContinuePanel1Layout.setHorizontalGroup(
            loginToContinuePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 260, Short.MAX_VALUE)
        );
        loginToContinuePanel1Layout.setVerticalGroup(
            loginToContinuePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 169, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(loginToContinuePanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loginToContinuePanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(400, 400, 400))
        );

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 260, 860));

        personNameLabel.setText("Name:");
        jPanel1.add(personNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 220, 120, -1));

        emailIdPersonLabel.setText("Email ID:");
        jPanel1.add(emailIdPersonLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 280, 70, -1));

        phonePersonalLabel.setText("Phone Number:");
        jPanel1.add(phonePersonalLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 340, 100, -1));

        cityLabel.setText("City:");
        jPanel1.add(cityLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 390, 40, -1));

        stateLabel.setText("State");
        jPanel1.add(stateLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 450, 40, -1));

        countryLabel.setText("Country:");
        jPanel1.add(countryLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 510, 60, -1));

        genderLabel.setText("Gender");
        jPanel1.add(genderLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 570, 60, -1));

        ageLabel.setText("Age:");
        jPanel1.add(ageLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 630, 60, -1));
        jPanel1.add(addressTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 500, 200, 130));

        nameTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTxtFieldActionPerformed(evt);
            }
        });
        jPanel1.add(nameTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 220, 150, -1));
        jPanel1.add(emailIdTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 280, 150, -1));
        jPanel1.add(phnNumberTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 340, 150, -1));
        jPanel1.add(cityTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 390, 150, -1));
        jPanel1.add(stateTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 450, 150, -1));
        jPanel1.add(countryTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 510, 150, -1));
        jPanel1.add(genderTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 570, 150, -1));
        jPanel1.add(ageTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 630, 150, -1));

        createPatientBtn.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        createPatientBtn.setText("UPDATE");
        createPatientBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createPatientBtnActionPerformed(evt);
            }
        });
        jPanel1.add(createPatientBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 740, 300, 80));

        personIdLabel1.setText("ID:");
        jPanel1.add(personIdLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 150, 70, -1));
        jPanel1.add(idTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 150, 150, -1));

        communityNameLabel.setText("Community Name:");
        jPanel1.add(communityNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 390, 130, -1));
        jPanel1.add(communityNameTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 390, 200, -1));

        addressLabel.setText("Address:");
        jPanel1.add(addressLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 520, 130, -1));

        zipCodeLabel.setText("ZipCode:");
        jPanel1.add(zipCodeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 450, 130, -1));
        jPanel1.add(zipCodeTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 450, 200, -1));

        photoLabel.setBackground(new java.awt.Color(255, 255, 255));
        photoLabel.setOpaque(true);
        jPanel1.add(photoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 180, 190, 160));

        jLabel7.setText("Image");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 260, 90, -1));

        browseButton.setText("Browse");
        browseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseButtonActionPerformed(evt);
            }
        });
        jPanel1.add(browseButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 350, -1, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void logoutLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutLabelMousePressed
        // TODO add your handling code here:

        RbacApplicationContext rbacApplicationContext = RbacApplicationContext.getInstance();
        rbacApplicationContext.setRoleContext(null);
        rbacApplicationContext.setUser(null);
        JOptionPane.showMessageDialog(this, "Logged Out");
        HomeScreenNotDefault homeScreenNotDefault = new HomeScreenNotDefault();
        HomeScreen.homeScreen.getjSplitPane1().setRightComponent(homeScreenNotDefault);
        HomeScreen.homeScreen.getjSplitPane1().setDividerLocation(150);
    }//GEN-LAST:event_logoutLabelMousePressed

    private void logoutLabel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutLabel1MousePressed
        // TODO add your handling code here:

        RbacApplicationContext rbacApplicationContext = RbacApplicationContext.getInstance();
        rbacApplicationContext.setRoleContext(null);
        rbacApplicationContext.setUser(null);
        JOptionPane.showMessageDialog(this, "Logged Out");
        HomeScreenNotDefault homeScreenNotDefault = new HomeScreenNotDefault();
        HomeScreen.homeScreen.getjSplitPane1().setRightComponent(homeScreenNotDefault);
        HomeScreen.homeScreen.getjSplitPane1().setDividerLocation(150);
    }//GEN-LAST:event_logoutLabel1MousePressed

    private void nameTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTxtFieldActionPerformed

    private void createPatientBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createPatientBtnActionPerformed
        // TODO add your handling code here:
        int errorCount =0;
        StringBuffer errorNotifier = new StringBuffer();
        String id = null, name = null, emailId = null, phoneNumber = null, cityName = null, state = null,
        country = null, gender = null, age = null, insuranceId = null, communityName = null, zipCode = null,
        address = null;
        Image image = null;
       
            if(ValidationHelper.isInteger(idTxtField.getText()))
            {
                id = idTxtField.getText();
            }else{
                errorCount++;
                errorNotifier.append(errorCount).append(". Hospital ID should be an Integer\n");
            }
            if(ValidationHelper.isValidName(nameTxtField.getText()))
            {
                name = nameTxtField.getText();
            }else{
                errorCount++;
                errorNotifier.append(errorCount).append(". Name should be a String\n");
            }
            if(ValidationHelper.isValidEmailID(emailIdTxtField.getText())){
                emailId = emailIdTxtField.getText();
            }else{
                errorCount++;
                errorNotifier.append(errorCount).append(". Email Id should be in xyz@gmail.com format\n");
            }
            if(ValidationHelper.checkPhoneNumberWith10Digits(phnNumberTxtField.getText())){
                phoneNumber = phnNumberTxtField.getText();
            }else{
                errorCount++;
                errorNotifier.append(errorCount).append(". Phone number should be of 10 digits\n");
            }
            if(ValidationHelper.isValidName(cityTxtField.getText())){
                cityName = cityTxtField.getText();
            }else{
                errorCount++;
                errorNotifier.append(errorCount).append(". Phone number should be a String\n");
            }
            if(ValidationHelper.isValidName(stateTxtField.getText()))
            {
                state = stateTxtField.getText();
            }else{
                errorCount++;
                errorNotifier.append(errorCount).append(". State should be a String\n");
            }

            if(ValidationHelper.isValidName(countryTxtField.getText())){
                country = countryTxtField.getText();
            }else{
                errorCount++;
                errorNotifier.append(errorCount).append(". Country should be a String\n");
            }
            if(ValidationHelper.isValidName(genderTxtField.getText())){
                gender = genderTxtField.getText();
            }else{
                errorCount++;
                errorNotifier.append(errorCount).append(". Gender should be a String\n");
            }
            if(ValidationHelper.isInteger(ageTxtField.getText())){
                age = ageTxtField.getText();
            }else{
                errorCount++;
                errorNotifier.append(errorCount).append(". Age should be an Integer\n");
            }


            if(ValidationHelper.isValidName(communityNameTxtField.getText())){
                communityName = communityNameTxtField.getText();
            }else{
                errorCount++;
                errorNotifier.append(errorCount).append(". Community Name should be a String\n");
            }
            if(ValidationHelper.isInteger(zipCodeTxtField.getText())){
                zipCode = zipCodeTxtField.getText();
            }else{
                errorCount++;
                errorNotifier.append(errorCount).append(". Zipcode should be an Integer\n");
            }
            if(ValidationHelper.isValidName(addressTxtField.getText())){
                address = addressTxtField.getText();
            }else{
                errorCount++;
                errorNotifier.append(errorCount).append(". Address should be a String\n");
            }
             
            if(globalImage != null)
            {
                image=globalImage;
            }else{
                errorCount++;
                errorNotifier.append(errorCount).append(". Please select  a Image\n");
            }
            if(errorCount > 0 )
            {
                JOptionPane.showMessageDialog(this, errorNotifier.toString());
            }else{

                City city = new City(state, country,  cityName);
                Community community = new Community(city, communityName, country, zipCode);
                House house = new House(community, 7, 8);
                 
               this.person.setId(id);
               this.person.setName(name);
               this.person.setAge(Integer.parseInt(age));
               this.person.setEmailid(emailId);
               this.person.setGender(gender);
               this.person.setPhoneNumber(Long.parseLong(phoneNumber));
               this.person.setResidence(house);
               this.person.setImage(globalImage);
               
               JOptionPane.showMessageDialog(this, "Person Record Updated Successfully");
               
            }
       
          

    }//GEN-LAST:event_createPatientBtnActionPerformed
    private Image globalImage = null;
    private void browseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseButtonActionPerformed
        // TODO add your handling code here:
        
        JFileChooser jFileChooser = new JFileChooser();
        FileNameExtensionFilter fileNameExtensionFilter = new FileNameExtensionFilter("Choose your extension", "jpg");
        jFileChooser.setFileFilter(fileNameExtensionFilter);

        try {
            int selectedOperation = jFileChooser.showOpenDialog(this);
            if (selectedOperation == JFileChooser.APPROVE_OPTION) {
                File file = jFileChooser.getSelectedFile();
               String selectedImage = file.getAbsolutePath();

                JOptionPane.showInternalMessageDialog(null, "Are you sure you want this Photo?");

                ImageIcon imageIcon = new ImageIcon(selectedImage);
                Image imageDefault = imageIcon.getImage();
                Image imageDisplay = imageDefault.getScaledInstance(photoLabel.getWidth(), photoLabel.getHeight(), Image.SCALE_SMOOTH);
                globalImage = imageDisplay;
                photoLabel.setIcon(new ImageIcon(imageDisplay));
            }
        } catch (Exception e) {
            System.out.println("Exception occured while choosing image e= " + e.getMessage());
        }
    }//GEN-LAST:event_browseButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addressLabel;
    private javax.swing.JTextField addressTxtField;
    private javax.swing.JLabel ageLabel;
    private javax.swing.JTextField ageTxtField;
    private javax.swing.JButton browseButton;
    private javax.swing.JLabel cityLabel;
    private javax.swing.JTextField cityTxtField;
    private javax.swing.JLabel communityNameLabel;
    private javax.swing.JTextField communityNameTxtField;
    private javax.swing.JLabel countryLabel;
    private javax.swing.JTextField countryTxtField;
    private javax.swing.JButton createPatientBtn;
    private javax.swing.JLabel emailIdPersonLabel;
    private javax.swing.JTextField emailIdTxtField;
    private javax.swing.JLabel genderLabel;
    private javax.swing.JTextField genderTxtField;
    private javax.swing.JTextField idTxtField;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel loginToContinuePanel;
    private javax.swing.JPanel loginToContinuePanel1;
    private javax.swing.JLabel logoutLabel;
    private javax.swing.JLabel logoutLabel1;
    private javax.swing.JTextField nameTxtField;
    private javax.swing.JLabel personIdLabel1;
    private javax.swing.JLabel personNameLabel;
    private javax.swing.JTextField phnNumberTxtField;
    private javax.swing.JLabel phonePersonalLabel;
    private javax.swing.JLabel photoLabel;
    private javax.swing.JLabel stateLabel;
    private javax.swing.JTextField stateTxtField;
    private javax.swing.JLabel zipCodeLabel;
    private javax.swing.JTextField zipCodeTxtField;
    // End of variables declaration//GEN-END:variables

    
}
